# Generated by Django 3.1.4 on 2020-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('cash', models.FloatField(default=100000.0)),
                ('btc', models.FloatField(default=0.0)),
                ('eth', models.FloatField(default=0.0)),
                ('ltc', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
