# Generated by Django 3.1.4 on 2020-12-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201207_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='password',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='first_name',
            field=models.CharField(default='joe', max_length=200),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='last_name',
            field=models.CharField(default='bob', max_length=200),
        ),
    ]
